// Illustrative marketing previews only. No account or application data is read.
const examples={
 home:{name:'Home',color:'#cefa78',label:'Room in your budget',amount:'8 450',detail:'Spent <b>R 9 550</b>',meta:'Budget <b>R 18 000</b>',title:'A little clarity, with every slip.',rows:[['G','Groceries','Everyday essentials','R 642.50'],['F','Fuel','On the move','R 800.00']],footer:'Know what’s left. Decide what’s next.',meter:'53%'},
 shift:{name:'Shift',color:'#ffaf83',label:'Your shift, at a glance',amount:'2 455',detail:'Tips <b>R 365</b>',meta:'Tables <b>12</b>',title:'Every table tells a story.',rows:[['14','Table 14','Card payment','R 835.00'],['6','Table 6','Card payment','R 420.00']],footer:'The shift doesn’t lie.',meter:'72%'},
 cur:{name:'Curator',color:'#cbb7ff',label:'Left of the client float',amount:'6 800',detail:'Spent <b>R 3 200</b>',meta:'Float <b>R 10 000</b>',title:'The details, all together.',rows:[['G','Groceries','Client essentials','R 580.00'],['P','Pharmacy','Receipt attached','R 245.00']],footer:'From purchase to statement. In sync.',meter:'32%'},
 road:{name:'Road',color:'#a4d9f5',label:'Travel allowance remaining',amount:'3 950',detail:'Spent <b>R 2 050</b>',meta:'Allowance <b>R 6 000</b>',title:'A record of the road.',rows:[['F','Fuel','Business travel','R 850.00'],['P','Parking','Client visit','R 45.00']],footer:'Every trip. Every expense. Accounted for.',meter:'34%'}
};
function showExample(key){const d=examples[key];if(!d)return;document.querySelectorAll('[data-demo]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.demo===key));b.tabIndex=b.dataset.demo===key?0:-1});document.querySelector('.preview-card').style.setProperty('--preview-accent',d.color);document.getElementById('demoName').textContent=d.name;document.getElementById('demoLabel').textContent=d.label;document.getElementById('demoAmount').innerHTML='R '+d.amount+'<span>.00</span>';document.getElementById('demoDetail').innerHTML=d.detail;document.getElementById('demoMeta').innerHTML=d.meta;document.getElementById('demoListTitle').textContent=d.title;document.getElementById('demoFooter').textContent=d.footer;document.querySelector('.preview-meter i').style.width=d.meter;document.getElementById('demoRows').innerHTML=d.rows.map((r,i)=>'<div><span class="mini-icon '+(i?'blue':'')+'">'+r[0]+'</span><span>'+r[1]+'<small>'+r[2]+'</small></span><b>'+r[3]+'</b></div>').join('')}
const previewTabs=[...document.querySelectorAll('[data-demo]')];previewTabs.forEach((b,i)=>{b.addEventListener('click',()=>showExample(b.dataset.demo));b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%4;else if(e.key==='ArrowLeft')n=(i+3)%4;else if(e.key==='Home')n=0;else if(e.key==='End')n=3;else return;e.preventDefault();showExample(previewTabs[n].dataset.demo);previewTabs[n].focus()})});showExample('home');
